### ISSUE TITLE
Unable to get the token from https://spark.gameforge.com/api/v1/auth/thin/codes

### ISSUE THREAD

**Issue by mattia-lau** [morsisko/NosTale-Auth#4]
```json
{
    "error": {
        "message": "Not allowed to create code"
    }
}
```

**Comment by morsisko** [comment]
Are you sure you are using the newest version and passing your tnt-installation-id?

**Comment by mattia-lau** [comment]
> Are you sure you are using the newest version and passing your tnt-installation-id?

Yes, i'm sure. Even im using your pypi package. It is same

**Comment by morsisko** [comment]
What happens when you firstly login to the game using GF launcher, can you generate codes using this library then?

**Comment by mattia-lau** [comment]
> What happens when you firstly login to the game using GF launcher, can you generate codes using this library then?

It works now.. Can you share the Login Workflow as well?

here is my nodejs tcp connect. But i cannot receive any data
```typescript
socket.connect({ host: "79.110.84.75", port: 4000 }, () => {
    logger.info("Connected To Game Socket Server");
    socket.write("123123");
});

socket.on("data", (data) => {
    logger.info(`Received Data: ${data.toString("utf-8")}`);
});
socket.on("error", (err) => {
  logger.error(err);
});
socket.on("close", () => {
  logger.info("Disconnected From Game Socket Server");
});
```

**Comment by morsisko** [comment]
I think it's little out of topic for this repo, maybe your login_encrypt function is wrong
