### ISSUE TITLE
[Not Related to this repo] Clientless Bot..

### ISSUE THREAD

**Issue by mattia-lau** [morsisko/NosTale-Auth#5]
I'm developing the clientless bot, but im not sure the workflow. Can you please help?

my current workflow:
1. Create a socket to login server (host: "79.110.84.75", port: 4000)
2. Send the Login Packet
3. Received the following package
  `Recieve Package: NsTeST  1 {user} 2 2 1 
-99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 
-99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 
-99 0 -99 0 -99 0 -99 0 -99 0 -99 0 -99 0 {session} 206.253.175.57:4010:1:2.7.US-Cylloan(New) 206.253.175.57:4009:1:2.6.US-Cylloan(New) 206.253.175.57:4008:2:2.5.US-Cylloan(New) 206.253.175.57:4007:2:2.4.US-Cylloan(New) 206.253.175.57:4006:3:2.3.US-Cylloan(New) 206.253.175.57:4004:1:2.2.US-Cylloan(New) 206.253.175.57:4003:8:2.1.US-Cylloan(New) 79.110.84.175:4003:1:1.1.UK-NosCitadel 79.110.84.175:4008:1:1.5.UK-NosCitadel 
79.110.84.175:4010:0:1.7.UK-NosCitadel 79.110.84.175:4004:0:1.2.UK-NosCitadel 79.110.84.175:4006:0:1.3.UK-NosCitadel 79.110.84.175:4007:0:1.4.UK-NosCitadel 79.110.84.175:4009:0:1.6.UK-NosCitadel -1:-1:-1:10000.10000.1`
4. Disconnect with login socket
5. Create a socket to game server ( host: "206.253.175.57", port: 4003)
6. Send encrypted (session)
7. Send encrypted(user+' GF 0')
8. Send encrypted('thisisgfmode')

However i received the LOGIN FAIL\n message. Do you have any idea?

**Comment by GorlikItsMe** [comment]
why you send `FG 0` it is correct? i remeber it is `ORG 0` but maybe it changed

**Comment by mattia-lau** [comment]
> why you send `FG 0` it is correct? i remeber it is `ORG 0` but maybe it changed
> 
> 

Packet logger show it's FG 0. But I'm not sure I'm correct

**Comment by morsisko** [comment]
With this information you provided I would say your encryption routine is wrong.

**Comment by mattia-lau** [comment]
> With this information you provided I would say your encryption routine is wrong.

How come? All the encrypted packet is same as your crypto repo, also if the encryption is wrong, server may not response anything

**Comment by GorlikItsMe** [comment]
check what you have in `sessionId` becouse login packet was changed, maybe you have here wrong value

**Comment by morsisko** [comment]
You are supposed to increment "pacetNum" each packet, also you need to be sure server received the sessionId before sending next packet, you can add sleep after sending the sessionId, NosTale client sleeps for 800ms

**Comment by mattia-lau** [comment]
> check what you have in `sessionId` becouse login packet was changed, maybe you have here wrong value

I have confirm it many times

**Comment by mattia-lau** [comment]
> You are supposed to increment "packetNum" each packet, also you need to be sure server you received the sessionId before sending next packet, you can add sleep after sending the sessionId, NosTale client sleeps for 800ms

Yes.. I have already do in this way. But still get the login fail

**Comment by GorlikItsMe** [comment]
Did you find solution?
